### PR TITLE
[ios] scale overlayview to full screen, like the camera preview

### PR DESCRIPTION
**Pull request by BernsteinA**

### CODE REVIEW

**Comment by BernsteinA** [comment]
bump?

**Comment by macdonst** [comment]
@BernsteinA what issue does this resolve or new functionality does it add?

**Comment by BernsteinA** [comment]
This makes it so that when using a custom overlay on iOS, it scales to cover the entire camera.
Do you need me to open an Issue for it?

**Comment by macdonst** [comment]
@BernsteinA I'm just trying to get a handle on what is being changed and why. It would be great if the change was documented somewhere.

**Comment by BernsteinA** [comment]
@macdonst @renatoc8
does https://github.com/phonegap/phonegap-plugin-barcodescanner/commit/f0a8664182688eb5db78373832a114bc5e717379 resolve this issue?

**Comment by renatoc8** [comment]
It does. The issue was fixed by adding a call to "[self.overlayView
setFrame:bounds]" when initializing overlayView.

**Pull request closed without merging**
