### PR TITLE
Fixes crash when switching cameras

### PR DESCRIPTION
**Pull request by aserraric**
Fixes [#277](https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/277)

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
Thanks. What does the minSdk removal fix?

**Comment by aserraric** [comment]
Whoops, didn't mean to include that commit. I had to do this for [#233](https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/233) because my app need a higher minSdk.

**Comment by macdonst** [comment]
@aserraric it'd be better if you just re-did the PR. You don't even need to start a new one just do another push to your branch without the minsdk commit.

**Comment by aserraric** [comment]
My mistake was creating a PR from master instead of a branch. Redid the PR as [#292](https://github.com/phonegap/phonegap-plugin-barcodescanner/pull/292)

**Comment by enzor77** [comment]
I recompiled my ios app right now with this change but when I try to flip the camera on an iphone 6S ios 9.3.3, still crashing!

**Comment by aserraric** [comment]
I have an IPhone 6 (iOS 9.3.3), and it works for me. Can you confirm it crashes at that particular line of code?

**Pull request closed without merging**
