### PR TITLE
Used fixed version in gradle file to not break  android builds

### PR DESCRIPTION
**Pull request by sburnicki**
Fixes the problem described in #616

### CODE REVIEW

**Comment by jcesarmobile** [comment]
Thanks for the PR, but we are planning on doing this configurable so people can use a preference in the config.xml to be used by all plugins

**Comment by ippeiukai** [comment]
@jcesarmobile Any chance this fix be released as a patch version? Everyone in the team is getting this error today. We are switching this library to a git branch instead of npm version for now, but it clearly is a temporary solution.

**Comment by ippeiukai** [comment]
Just to let you know: we ended up using cordova-android-support-gradle-release plugin to specify the version of android support lib we like. You can scratch above comment.

**Comment by macdonst** [comment]
@sburnicki thanks for the PR but it's superseded by #621 where the user will have better control over the support library version that gets pulled in.

**Pull request closed without merging**
