### PR TITLE
Merge Telerik and PhoneGap's forks

### PR DESCRIPTION
**Pull request by EddyVerbruggen**
Hi guys,

A year ago the Wildabeast upstream repo was "abandoned" and this fork and Telerik's fork evolved. The PhoneGap fork got a lot of love from Microsoft and the Telerik fork focused on fixing issues on and adding small enhancements to iOS and Android.

Last week Microsoft's @nikhilkh contacted Telerik's @rdlauer and myself about a possible merge of Telerik's fork with PhoneGap's to create the ultimate BarcodeScanner plugin version and join efforts maintaining only one version.

So we agreed to merge our changes to this fork and keep our forks in sync as much as possible so everybody benefits. Note that the Telerik fork won't be removed after this merge since it's used in the [Telerik Platform](https://platform.telerik.com) which relies on stable releases we need full control over.

So now there's this big a** merge request which I've tested on iOS and Android. We didn't change much on the Windows platforms so I'm not expecting that to break but a little smoke test on all platforms won't hurt.

I've also added PR #210 to this PR as I liked how it handles Android M permissions better than I did on the Telerik fork :) .. so that one can be closed once this PR is merged.

Please don't take too long to merge it as the slightest commit to this repo will prevent an automatic merge.

Thanks in advance and looking forward to working with you guys on this plugin in the future!
Eddy

### CODE REVIEW

**Comment by nikhilkh** [comment]
@vladimir-kotikov, @sarangan12 to help merge this.@stevengill for FYI. We should do a release of this plugin once this is merged

**Comment by stevengill** [comment]
Wow. This looks great! Vladimir is already an owner on npm and I just added @EddyVerbruggen as a npm owner as well. Let me know if you need my help here.

**Comment by EddyVerbruggen** [comment]
Thanks for that @stevengill!

FYI - I've added a few more commits because when we initially forked the Wildabeast repo we removed a few files which weren't removed in this fork so this PR would removed them here as well. Which is not what I intend to do.

**Comment by vladimir-kotikov** [comment]
Did a quick review and some smoke testing on all main platforms - everything seems to be fine except one issue with iOS - when running the basic sample (without any `options` passed to `scan` method) i'm getting the following error in Xcode console
```
2016-05-04 15:49:50.900 HelloCordova[1260:2087813] *** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSRangeException> *** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array
```

Looks like the problem is caused by arguments conversion code in [www/barcodescanner.js#L74-L82](https://github.com/phonegap/phonegap-plugin-barcodescanner/blob/master/www/barcodescanner.js#L74-L82) - passing an empty object rather than `undefined` solves the problem for me.

@sarangan12, @EddyVerbruggen, could you please confirm that you see the same issue?

**Comment by EddyVerbruggen** [comment]
@vladimir-kotikov Thanks for finding that! I've just update the iOS code to cover this case 👍

**Comment by vladimir-kotikov** [comment]
Thanks, @EddyVerbruggen. @sarangan12, would you like to take a look as well?

**Comment by nikhilkh** [comment]
I checked with @sarangan12 - Vladimir - you should go ahead and merge this if you're ready.

**Comment by vladimir-kotikov** [comment]
Thanks. This pull request has been integrated manually.

**Pull request closed without merging**
