### PR TITLE
Adds saveHistory flag

### PR DESCRIPTION
**Pull request by renanbandeira**
Barcode scanner stores a history of scanned barcodes. The idea here is to set it on the phonegap lib.

Issue: https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/350

### CODE REVIEW

**Comment by renanbandeira** [comment]
I don't know if it's exactly what you wanted, but to be honest, I think it was better. Basically the plugin will read the `saveHistory` from the user preference defined in `config.xml`

**Comment by macdonst** [comment]
@renanbandeira You're right it was better. I should do code reviews before morning ☕️ . Can you revert 523501d8d7199928093c8dbebf67d9358476cc77? As I now read it with a clear head you are reading the `saveHistory` property from the options object. 

Did you look at iOS at all?

**Comment by jcesarmobile** [comment]
I don't think iOS saves the history.
This should be documented on the README.md

**Comment by renanbandeira** [comment]
Added prop to README.md

**Pull request merged**
