### PR TITLE
Introduces universal windows platform, improvements and bugfixing

### PR DESCRIPTION
**Pull request by vladimir-kotikov**
This PR is a replacement for https://github.com/wildabeast/BarcodeScanner/pull/230: 

* Adds support for windows platform and shares proxy code between windows8 and windows platforms
* Adds some minor UI improvements
* Fixes bug when cancel button crashed application (reported as https://github.com/wildabeast/BarcodeScanner/issues/148)
* Enables autofocus on supported camera devices
* Includes winmd source as subproject instead of shipping prebuilt winmd component

### CODE REVIEW

**Comment by dougestey** [comment]
This is the first PR I've seen for this plugin which builds and runs without errors in the 8.1 (windows) environment on a Windows Phone. Unfortunately, I'm still getting a green screen when opening the scanner.

**Comment by sgrebnov** [comment]
Tested on Windows :+1:

**Comment by dougestey** [comment]
Does anyone have this working on Windows Phone? 

@vladimir-kotikov better yet - is it intended to?

**Comment by vladimir-kotikov** [comment]
Hey @dougestey, just tried again to run on Lumia 1520, all works fine.
I recently saw several issues with MediaCapture API on different devices, maybe this is your case. Could you please try it on another device?

**Comment by dougestey** [comment]
@vladimir-kotikov thanks so much for your response - I will build on a Lumia 930 today and get back to you. I believe my issue might be that I'm building for 8.1/windows instead of 8.0/wp.

**Comment by dougestey** [comment]
@vladimir-kotikov thanks for the tip. this PR (and now master) does build on the 930 on 8.1/windows. Now I just need to figure out why I can't get it to focus.

**Comment by vladimir-kotikov** [comment]
@dougestey for diagnosing focus problems - try to put several breakpoints around [this](https://github.com/phonegap/phonegap-plugin-barcodescanner/pull/1/files#diff-8f683c1d335324b3eff6aa003b337182R61) line and check if your device support auto/continuous focus modes.

**Comment by dougestey** [comment]
@vladimir-kotikov the 930 is passing all of those checks, and I'm able to console.log() the focusSettings object, which reveals that continuous mode is properly set - it's just not working in practice (this is strange since we essentially have the same device.)

Anyway, I was able to create a focus button and manually call focusAsync(), which works, so I'm happy: https://github.com/dougestey/phonegap-plugin-barcodescanner/commit/b8fc83b6f230be8d64504c6a4779c7b370116c94

It seems the MediaCapture API is still a bit buggy, so I am willing to chalk my problems up to that and call it a day: https://marekcodes.wordpress.com/2015/02/23/the-horror-of-the-new-windows-phone-8-1-camera-api/

**Comment by angegar** [comment]
I am using the plugin on Windows 8.1 and it seems to have bug. I am able to start the camera to scan but it opens a black screen we the cancel button at the bottom rigth corner. When i click cancel i am able to go back to the previous page but the application crash.

Can someone please help on this issue ?

Thank you in advance

**Pull request merged**
