### PR TITLE
Android zxing integration

### PR DESCRIPTION
**Pull request by kbytesys**
I've get rid of the old embed zxing library and switched to the android-integration.

The plugin will use always the newer barscanner app installed in the phone without any maintenance needs.

This solves https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/137 but I think that this pr could also solve  https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/139 , https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/141 and maybe other issues.

### CODE REVIEW

**Comment by kbytesys** [comment]
Travis fails to build because some error on ios platform, could you retry the build please?

**Comment by vrushankshukla** [comment]
Hi,

I used this in my Cordova app, and tested with android 6.1. It gives the same error. 

"Unfortunately there was an error with the Android-Camera. It could be that you need to restart your device."

But the good news is, app can scan now PDF417. Before with phonegap-plugin-barcodescanner, it didn't scan PDF417, but now its working. 

But still Android 6.1, it has the same error.

Sicerely

**Comment by kbytesys** [comment]
@vrushankshukla hi

did you used the android-zxing-integration branch?

please consider that now the phonegap plugin doesn't open the camera anymore.

Did you get the same error with the zxing barscanner app sometime?

**Comment by vrushankshukla** [comment]
Hi,

I just remove the phonegap-plugin-barcodescanner and used following command and test the app

cordova plugin add https://github.com/kbytesys/phonegap-plugin-barcodescanner.git.

How can I use android-zxing-integration branch? I didn't get it.

**Comment by kbytesys** [comment]
@vrushankshukla try this url https://github.com/kbytesys/phonegap-plugin-barcodescanner/tree/android-zxing-integration

or get the zip from that link (or clone that branch) and do

cordova plugin add directoryofunzippedfile

**Comment by vrushankshukla** [comment]
Hi

I add this plugin to my app and when I hit scan button first time, it ask to install zxing barcode scanner app. I installed it and it worked with Android 6.1 too. But thing is, zxing app is running in the background of my app.

**Comment by kbytesys** [comment]
@vrushankshukla yep It's the normal behaviour. Btw the zxing app will be present only in your task manager. No services or running app as I known.

**Comment by vrushankshukla** [comment]
@kbytesys  really appreciate your great help and guidance. You are awesome.

But Zxing  Barcode scanner app installed separately on my device. Actually I want to develop standalone barcode scanning app, but the problem is phonegap-plugin-barcodescanner only work till Android 5.x.x.

**Comment by kbytesys** [comment]
@vrushankshukla the plugin uses the (3 years) old zxing library atm and it's really hard to update to the newest release because the zxing code has grown too much.

Somebody could try to use the zxing android-core library, but I think that this plugin does not have enough manpower.

I think that is better to let zxing to develop new features, fix bugs and support new phones and android releases for us :smile:

**Comment by vrushankshukla** [comment]
@kbytesys  yes, understood your point. Is there any free plugin like this for barcode scanner? Also this plugin says, it has support for PDF417 in android, but still its struggling to scan PDF417 barrcode.

**Comment by kbytesys** [comment]
@vrushankshukla As I known  there are no alternatives atm.

Btw the zxing app is free and released under the apache 2.0 license.

Note: PDF 417 is a beta feature, take a look to https://github.com/zxing/zxing for info

**Comment by multilexus** [comment]
Hi all! I got it to work on Android with PDF417 by adding the following line in my plugin's BarcodeScanner.java file:

intentScan.putExtra("SCAN_FORMATS","CODE_39,CODE_93,CODE_128,DATA_MATRIX,ITF,CODABAR,EAN_13,EAN_8,UPC_A,QR_CODE,PDF_417");

After that i had to recompile the android platform code. Easy way to do it is to remove platform, then add platform and rebuild.

Cheers,
Alex $

**Comment by barryvdh** [comment]
This looks great! I've tried your fork and it works for me. The BarcodeScanner is installed on most phones and indeed free, so no problem for me.
This also fixes #167 for me.

**Comment by edward962** [comment]
Will it work for Android AZTEK?

**Comment by macdonst** [comment]
@kbytesys thanks for the PR but that's not the direction we want to go in with this plugin. We don't want users to have to install a separate app to do the scanning.

**Pull request closed without merging**
