### PR TITLE
Fix WP8

### PR DESCRIPTION
**Pull request by sebastieno**
Force the focus of the camera
Fix the plugin when the back button is pressed
Fix the plugin when the app is tombstoned

### CODE REVIEW

**Comment by cmgustavo** [comment]
+1 to merge

**Comment by matiu** [comment]
+1

**Comment by TimBarham** [comment]
Hey @sebastieno - there are some merge conflicts with recent changes that have gone in, and maybe some overlap in the actual fixes. Could you take a look and sort out the merge conflicts? Thanks!

**Comment by angegar** [comment]
Hello, i tried to use the master version but i am encountering issues. When i use it i receive the following exception : 

in src/windows/BarcodeScannerProxy.js (Reader: function called with too few arguments)

i use the plugin in this way : cordova.plugins.barcodeScanner.scan(successCallback,errorCallback)

I am wondering if it is linked with the merge you are previously talking about.

**Comment by SingleID** [comment]
How can I use this plugin with phonegap build? thanks in advance

**Comment by keithFrontiers** [comment]
Dear Dan,

 

I will repackage the source and you guys can build a new ipa to use it.

 

Best regards,

Keith Ho

**Comment by bau720123** [comment]
+1
when I use "cordova.plugins.barcodeScanner.scan" method in wp8
the app will immediately shut down
android and iOS is work perfect !!!

**Comment by bau720123** [comment]
hi @keithFrontiers 
use this plugin in PGB，you can use this way in your config.xml
```
<gap:plugin name="phonegap-plugin-barcodescanner" source="npm" version="3.1.0" />
```

**Comment by bau720123** [comment]
hi all
for now I am using 
```
<gap:plugin name="phonegap-plugin-barcodescanner" source="npm" version="3.1.2" />
```
when I use scan method in wp8，it seem can scan the QR CODE perfectly，but after scan，nothing happened...
no trigger on alert，just "nothing"

**Comment by macdonst** [comment]
Dropping windows8 support so we will not merge.

**Pull request closed without merging**
