### PR TITLE
added grade file to disable Missing/Extra Translation lint

### PR DESCRIPTION
**Pull request by sckoh**
added grade file to disable Missing/Extra Translation lint to avoid
cordova build —release android error

https://github.com/wildabeast/BarcodeScanner/issues/276
https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/80
https://github.com/meteor/meteor/issues/5373
https://github.com/driftyco/ionic-package-hooks/pull/3

### CODE REVIEW

**Comment by sckoh** [comment]
why does it fail?
i am able to build ios/android successfully

**Comment by johnvic** [comment]
Any news on this commit/PR? we are having the same issue and we cannot build our app through Phonegap Build.

**Comment by bau720123** [comment]
I have the same problem
android build error

**Comment by johnvic** [comment]
Are you also using Phonegap Build Web service @bau720123 ?

**Comment by bau720123** [comment]
hi @johnvic 
yes
I am using PGB (cli-5.4.1)

in Cordova Cli，we can use a file that called "build-extras.gradle" to solve this problem (put this file in Android folder)
but in PGB，there is no way can do such kind of behavior

**Comment by johnvic** [comment]
Yeah, unfortunately I cannot add the file in the PGB webservice as others suggest in the forum and in the error log itself. Frustrating..I hope this PR will be merged. It seems this will fix the issue.

**Comment by debugerr** [comment]
Same problem here. We would need this to get phonegap build to work again. There are a lot of users affected by this: http://community.phonegap.com/nitobi/topics/build-fails-due-to-translation-error?utm_source=notification&utm_medium=email&utm_campaign=new_reply&utm_content=topic_link

**Comment by renevaessen** [comment]
Same here, please fix this.

**Comment by debugerr** [comment]
@sckoh Any update on this?

**Comment by sckoh** [comment]
Author is not replying here.
And I have no idea why the CI is failing. Seems like all the pull request
is failing in the CI build

**Comment by sckoh** [comment]
@debuger
U can temporary use my fork

**Comment by goya** [comment]
add the translations?

**Comment by 5lao2** [comment]
Any update on this, we can fix this by modify xml in android folder, but once we rm the platform and re-add, the issue will show again.

**Pull request closed without merging**
