### PR TITLE
FIXED: iOS orientation and rotation bug.

### PR DESCRIPTION
**Pull request by MikelEiza**

### CODE REVIEW

**Comment by mike-eason** [comment]
Do we really need all those new line additions?

**Comment by MikelEiza** [comment]
No, not really. I think that they were added automatically by my text
editor. If you want I can send another pull request.



Enviado con MailTrack
<https://mailtrack.io/install?source=signature&lang=es&referral=mikeleiza@gmail.com&idSignature=23>

2016-03-01 13:20 GMT+01:00 mike-eason <notifications@github.com>:

**Comment by vash15** [comment]
Hi @MikelEiza , I tried your code but the XCode returned an error the first time I opened Barcode Scanner.

> *** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSRangeException> Cannot remove an observer <CDVSplashScreen 0x124e22d50> for the key path "frame" from <UIView 0x124d37050> because it is not registered as an observer.

I'm using XCode 7.3.1 with cordova-ios 4.1.1

**Comment by mestremuten** [comment]
Works great!!!

iOS 9.3.2
cordova-ios 4.1.1
cordova-plugin-barcodescanner 5.0.0
cordova CLI 6.2 and ios-deploy 1.8.3 (no xcode)

That's the only fix that made it work in landscape mode without screwing up my App's viewport. 

I think this also should fix this issue: https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/40

**Comment by daserge** [comment]
Tested on iPad iOS 8.1 and iPhone 6 iOS 9.3.1 - works well.

**Comment by owq** [comment]
Awesome fix. Thanks so much!
Tested on iPad iOS 9.3.2.

**Comment by EddyVerbruggen** [comment]
This fixes the black border in landscape mode but I can't scan a [code 128](https://www.google.nl/search?q=barcode+128&espv=2&tbm=isch&tbo=u&source=univ&sa=X&ved=0ahUKEwjz2ZT0qq_NAhUBB8AKHb_RCm0QsAQIMg&biw=1249&bih=778) this way. Rotating to portrait fixes this.

I'm sure this works fine for QR codes but not for 2D barcodes I'm afraid.

Do you guys have similar experience with this change applied?

**Comment by EddyVerbruggen** [comment]
Found a way - needs another change. Will test a bit and update the repo.

**Comment by EddyVerbruggen** [comment]
Thanks @MikelEiza, I only had to add a little tweak to make 2D barcode scanning work on landscape as well. I had to manually merge it due to the merge conflicts, so closing this. Available in 5.0.1.

**Pull request closed without merging**
