### PR TITLE
Add Windows 10 Support

### LINKED ISSUE #87: Can this run on a windows 10 build
I would like to build this for windows 10 but it fails store submission please help.

### PR DESCRIPTION
**Pull request by RyanWFiorini**
Created a Windows Runtime Component (Universal Windows) for all platform types for the zxing.winmd.  Created a Windows Runtime Component (Universal Windows) for the WinRTBarcodeReader.  Added it to the plugin and applied a version attribute to the framework entries.

Fixes #87

### CODE REVIEW

**Comment by vladimir-kotikov** [comment]
@TimBarham, this looks good, can we merge this?

@RyanWFiorini, only one question: is it possible to reuse the same files (at least `Reader.cs` and ZXing library for AnyCPU, as they seems to be equal) for both Win8 and Win10 versions of the component?

**Comment by RyanWFiorini** [comment]
I noticed you closed this request.  I didn't see the previous message to me.  I can use the same file for both projects.  Do you want to reopen the request and I will make the changes?

**Comment by vladimir-kotikov** [comment]
No, this is not needed, because your changes pulled into master in https://github.com/phonegap/phonegap-plugin-barcodescanner/commit/9c2da016e4ddbd973a596568c750b7bb48ea4409. Thanks!

**Comment by vladimir-kotikov** [comment]
Also I played with new mediaCapture APi in Windows 10 and realized, that we don't need for this WinMD component anymore. The only thing required is ZXing assemblies, rebuilt for Win10 from your PR

**Pull request closed without merging**
