### PR TITLE
Add new barcodes for iOS

### PR DESCRIPTION
**Pull request by jlowe234**
The iOS update to resolve issue #312 by switching to AVMetadataObjectDelegate enables support for Aztec, PDF 417, and Code 93. Because of this, the AVOutput required some minor updates to enable reading and returning values for these barcode types.

The attached barcodes were the test cases.
PDF417 value: "This PDF417 code"
pdf417 - this pdf417 code

Aztec value: "test aztec"
aztec - test aztec

Code 93 value: "123ABC93"
code93 - 123abc93

Fixes: #335, #312

### CODE REVIEW

**Comment by jgcaruso** [comment]
I can confirm that the changes to CDVBarcodeScanner.mm fix the app crashing issue.

As well, I am now able to scan the CODE 93 barcode samples that I had on my desk that previously only worked on my Android build.

**Comment by inzi** [comment]
How do I download and test *this* version to test issue #312 as well as PDF417 (#335)?
Via the "Don't try this at home" method from #312 thread?

**Comment by jlowe234** [comment]
I would assume you would do it in a similar way that was outlined in the #312 thread.

Something like below:
`<plugin name="phonegap-plugin-barcodescanner" spec="https://github.com/jlowe234/phonegap-plugin-barcodescanner.git" />`

**Comment by EddyVerbruggen** [comment]
Top job! Released with 6.0.3.

**Comment by jrobichaud** [comment]
This pull request introduced a bug with UPC_A.

Prior to this PR [this code](https://github.com/phonegap/phonegap-plugin-barcodescanner/files/586733/codedb42a5efb3392c5acb9892435df49371.pdf)
 would scan "776312900108" but now it scans "0776312900108".

**Pull request merged**
