### PR TITLE
send callbacks on dismissViewControllerAnimated completion

### PR DESCRIPTION
**Pull request by jcesarmobile**
Changed barcodeScanDone method to use a block, so it sends the
callbacks to the javascript side when the barcode scanner view
controller has been completely dismissed.
It was causing problems with the dialogs plugin if you used a dialog on
the success or error callback as the barcode scanner view was being dismissed and couldn't present a dialog over it.

### CODE REVIEW

**Comment by tony--** [comment]
@jcesarmobile - Do you know if this PR is still relevant? Just wondering if this was addressed in some other way in 5.0.0...

**Comment by jcesarmobile** [comment]
I don't think this has been addressed in some other way.
The dialogs problem won't appear now because I fixed another bug on the dialogs plugin that avoids the presentation of the dialog on a ViewController that is being dismissed, but if this isn't merged, there can be problems with other plugins that might present a ViewController with the QR result (inAppBrowser comes to my mind if you scan an url and try to open it). 

Now I have permissions on this repo and can merge it, but should figure out why Travis failed first. 
I'm in the middle of a travel, so I'll try to take a look next week.

**Comment by daserge** [comment]
@jcesarmobile, I've restarted the build and it passed.

**Comment by jcesarmobile** [comment]
Thanks, I'll rebase because it has conflicts now, hope it passes again

**Comment by jcesarmobile** [comment]
Rebased

@EddyVerbruggen can you review it?

**Comment by EddyVerbruggen** [comment]
Look good, thanks! 👍

**Comment by jcesarmobile** [comment]
merged

**Pull request merged**
