### PR TITLE
iOS & Windows: a collection of some different extensions and a few tiny bug-fixes / memory leaks

### PR DESCRIPTION
**Pull request by convey-mane**
In our project we needed many (well, OK, some) extensions. I did commit one at a time, giving each a descriptive title and a hopefully sufficient comment, so you could check each on it's own (is this OK for you?). Where necessary things are parametrizable via new preferences, which is also documented in the README.md.

I know, that @wildabeast also worked on that landscape topic (https://github.com/wildabeast/BarcodeScanner/commit/7226982993fa95732ee487c5c5d032b34a983207 and https://github.com/wildabeast/BarcodeScanner/commit/d33ba135fa232aba2b78e8370ad8cc467dca0369), I even took some ideas from him – but did do some other things different (on one I already commented: https://github.com/wildabeast/BarcodeScanner/commit/d33ba135fa232aba2b78e8370ad8cc467dca0369#comments) and imho, well, better(?). On the other hand I also implemented it compile-time configurable, as he suggested, even if we don't need that ourselves.
It would also be a resolution for #40 (landscape overall and especially that thing with that ugly black bar resulting from different orientations between the calling App and the plugin itself).

The thing with the flash/torch is also something, others already are longing for (#36 and #10).

And as I was already in it, I even implemented another thing, we probably won't need, but someone else requested (and did not fully implement it himself): #88 – inverse QR-codes.

Hoping you like our extensions!

P.S.: Sorry for
- not labelling the commits with "iOS";
- the distorted links in the comments;
- the starting hiccups;
- that seesaw with the version numbering (my colleagues wanted to know exactly what status they have).

### CODE REVIEW

**Comment by vladimir-kotikov** [comment]
@convey-mane, @convey-gilbert, FYI, orientation change support for Windows was added in https://github.com/phonegap/phonegap-plugin-barcodescanner/commit/51216ff3dd0375a694eb4f9352bb78046ae47505

**Comment by operacha** [comment]
Has the flashlight/torch toggle been added? Its a very useful feature to have for scanning in dark situations.

**Comment by diego-vieira** [comment]
will this get merged?

**Comment by sagrawal14** [comment]
Sorry, never mind, I mis-understood the comment. The feature is already there for iOS.

**Comment by vladpke** [comment]
Any news on when this pull request will be merged?

**Comment by jcesarmobile** [comment]
This can't be merged as is, would need a major refactor as the plugin has changed a lot since the PR was sent, so I will close it.
Please, for future PRs, send smaller changes so it can be evaluated easily, that will increase the chances of being merged.

**Pull request closed without merging**
