### PR TITLE
NOMERGE: Add package.json on tests to fix travis

### PR DESCRIPTION
**Pull request by jcesarmobile**

### CODE REVIEW

**Comment by macdonst** [comment]
@jcesarmobile is this good to be merged?

**Comment by jcesarmobile** [comment]
No, the package.json wasn't the real problem here, I think it's in cordova-paramedic using nofetch.

Some of the commits are just tests, so don't merge this.

**Comment by macdonst** [comment]
@jcesarmobile kk, just making sure.

**Comment by macdonst** [comment]
@jcesarmobile I ended up killing the cordova-paramedic stuff for now as it wasn't actually adding any value and we'll rely on regression tests for now.

**Pull request closed without merging**
